"""add user is_active

Revision ID: 12e1448d29b9
Revises: 5ad1e405f655
Create Date: 2026-07-16 15:31:41.439578

"""
from alembic import op
import sqlalchemy as sa


revision = '12e1448d29b9'
down_revision = '5ad1e405f655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
